### ISSUE TITLE
Remove your Spotify cookie from the config file

### ISSUE THREAD

**Issue by raitonoberu** [manit989/dotfiles#1]
Please remove your Spotify cookie from the sptlrx [config](../blob/master/.config/sptlrx/config.yaml). It can be used to literally log into your account. Also, logging out of the account in the browser you copied it from and logging in again should make it unusable (not sure).

I will add it to the project's README as soon as possible.

**Comment by manit989** [comment]
i didn't know that , thanks for mentioning
